trigger:
  branches:
    include:
      - main  # Trigger on main branch updates
  paths:
    include:
      - frontend/*
      - Dockerfile.api
pool:
  name: 'Default'  # Specify the agent pool name
  demands:
    - agent.name -equals nensijsk  # Target the specific agent "nensijsk"

variables:
  dockerRegistryServiceConnection: 'task2-dockerhub-connection'  # Docker Hub service connection name
  imageNameApi: 'yatricloud/ransomware-dashboard-api'
  imageNameFrontend: 'yatricloud/ransomware-dashboard-frontend'
  azureWebAppName: 'task2-web-app'  # Azure Web App name
  dockerComposeFile: 'docker-compose.yml'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build React App'
  condition: |
    contains(variables['Build.SourceVersion'], 'frontend')  

- task: Docker@2
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageNameFrontend)
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'  # Adjust to correct Dockerfile path for frontend
    tags: |
      latest
  displayName: 'Build and Push Frontend Docker Image'
  condition: |
    contains(variables['Build.SourceVersion'], 'frontend')  

- task: Docker@2
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageNameApi)
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile.api'  # Adjust to correct Dockerfile path for API
    tags: |
      latest
  displayName: 'Build and Push API Docker Image'
  condition: |
    not(contains(variables['Build.SourceVersion'], 'frontend'))  