trigger:
  branches:
    include:
      - main  # Trigger on main branch updates

pool:
  name: 'Default'  # Specify the agent pool name
  demands:
    - agent.name -equals jskagent  # Ensure it uses the specified agent

variables:
  dockerRegistryServiceConnection: 'task2-dockerhub-connection'  # Docker Hub service connection name
  imageNameApi: 'yatricloud/ransomware-dashboard-api'
  imageNameFrontend: 'yatricloud/ransomware-dashboard-frontend'
  azureWebAppName: 'task2-web-app'  # Azure Web App name
  dockerComposeFile: 'docker-compose.yml'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build React App'

- task: Docker@2
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageNameApi)
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile.api'  # Adjust to the correct Dockerfile path for API
    tags: |
      latest
  displayName: 'Build and Push API Docker Image'

- task: Docker@2
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageNameFrontend)
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'  # Adjust to correct Dockerfile path for frontend
    tags: |
      latest
  displayName: 'Build and Push Frontend Docker Image'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'your-azure-subscription'  # Replace with your Azure subscription name
    appName: $(azureWebAppName)
    containers: |
      $(imageNameApi):latest
      $(imageNameFrontend):latest
    dockerComposeFile: $(dockerComposeFile)
    configuration: '$(System.DefaultWorkingDirectory)/docker-compose.yml'  # Ensures the latest file is used
    startupCommand: 'docker-compose up -d'
  displayName: 'Deploy to Azure Web App using Docker Compose'
