trigger:
  branches:
    include:
      - main  # Trigger on main branch updates

pool:
  name: 'Default'  # Specify the agent pool name
  demands:
    - agent.name -equals nensijsk  # Use specific agent "nensijsk"

variables:
  dockerRegistryServiceConnection: 'task2-dockerhub-connection'  # Docker Hub service connection name
  imageNameApi: 'yatricloud/ransomware-dashboard-api'
  imageNameFrontend: 'yatricloud/ransomware-dashboard-frontend'
  azureWebAppName: 'task2-web-app'  # Azure Web App name
  dockerComposeFile: 'docker-compose.yml'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build React App'

# Conditionally build and push the frontend Docker image if changes are detected in the frontend directory
- task: Docker@2
  condition: contains(variables['Build.Changes'], 'frontend/')  # Run only if files in frontend/ are modified
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageNameFrontend)
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'  # Adjust to correct Dockerfile path for frontend
    tags: |
      latest
  displayName: 'Build and Push Frontend Docker Image'

# Conditionally build and push the API Docker image if changes are detected outside the frontend directory
- task: Docker@2
  condition: not(contains(variables['Build.Changes'], 'frontend/'))  # Run only if files outside frontend/ are modified
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageNameApi)
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile.api'  # Adjust to correct Dockerfile path for API
    tags: |
      latest
  displayName: 'Build and Push API Docker Image'