version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Build the frontend from its directory
      dockerfile: Dockerfile  # Specify the Dockerfile for the frontend
    ports:
      - "3000:3000"  
    depends_on:
      - api  # Ensure the API is available before starting the frontend

  api:
    build:
      context: .  # Build the API from the root directory
      dockerfile: Dockerfile.api  # Specify the Dockerfile for the API
    ports:
      - "5000:5000"  
    environment:
      - FLASK_APP=app.py
      - MONGO_URI=mongodb+srv://nensi:yatricloud@cluster0.mongodb.net/ransomware_db?retryWrites=true&w=majority